int8 "A Env: Key Scaling"
int8 "B Env: Key Scaling"
int8 "C Env: Key Scaling"
int8 "D Env: Key Scaling"
int8 "E Env: Key Scaling"
int8 "F Env: Key Scaling"
int8 "X Env: Key Scaling"
int8 "Z Env: Key Scaling"
int8 "? Env: Key Scaling"

int8 "A Env: Vel Scaling"
int8 "B Env: Vel Scaling"
int8 "C Env: Vel Scaling"
int8 "D Env: Vel Scaling"
int8 "E Env: Vel Scaling"
int8 "F Env: Vel Scaling"
int8 "X Env: Vel Scaling"
int8 "Z Env: Vel Scaling"
int8 "? Env: Vel Scaling"

int8 "A AmpMod PB Up"
int8 "B AmpMod PB Up"
int8 "C AmpMod PB Up"
int8 "D AmpMod PB Up"
int8 "E AmpMod PB Up"
int8 "F AmpMod PB Up"
int8 "X AmpMod PB Up"
int8 "Z AmpMod PB Up"

int8 "?"

int8 "A AmpMod PB Dn"
int8 "B AmpMod PB Dn"
int8 "C AmpMod PB Dn"
int8 "D AmpMod PB Dn"
int8 "E AmpMod PB Dn"
int8 "F AmpMod PB Dn"
int8 "X AmpMod PB Dn"
int8 "Z AmpMod PB Dn"

int8 "6"

int8 "A AmpMod PB AT"
int8 "B AmpMod PB AT"
int8 "C AmpMod PB AT"
int8 "D AmpMod PB AT"
int8 "E AmpMod PB AT"
int8 "F AmpMod PB AT"
int8 "X AmpMod PB AT"
int8 "Z AmpMod PB AT"

int8 "18"

int8 "A AmpMod Mod"
int8 "B AmpMod Mod"
int8 "C AmpMod Mod"
int8 "D AmpMod Mod"
int8 "E AmpMod Mod"
int8 "F AmpMod Mod"
int8 "X AmpMod Mod"
int8 "Z AmpMod Mod"

int8 "17"

int8 "A AmpMod PB Breath"
int8 "B AmpMod PB Breath"
int8 "C AmpMod PB Breath"
int8 "D AmpMod PB Breath"
int8 "E AmpMod PB Breath"
int8 "F AmpMod PB Breath"
int8 "X AmpMod PB Breath"
int8 "Z AmpMod PB Breath"

int8 "16"

int8 "A AmpMod PB Ctrl 1"
int8 "B AmpMod PB Ctrl 1"
int8 "C AmpMod PB Ctrl 1"
int8 "D AmpMod PB Ctrl 1"
int8 "E AmpMod PB Ctrl 1"
int8 "F AmpMod PB Ctrl 1"
int8 "X AmpMod PB Ctrl 1"
int8 "Z AmpMod PB Ctrl 1"

int8 "19"

int8 "A AmpMod PB Ctrl 2"
int8 "B AmpMod PB Ctrl 2"
int8 "C AmpMod PB Ctrl 2"
int8 "D AmpMod PB Ctrl 2"
int8 "E AmpMod PB Ctrl 2"
int8 "F AmpMod PB Ctrl 2"
int8 "X AmpMod PB Ctrl 2"
int8 "Z AmpMod PB Ctrl 2"

int8 "23"

int8 "A AmpMod PB In Env"
int8 "B AmpMod PB In Env"
int8 "C AmpMod PB In Env"
int8 "D AmpMod PB In Env"
int8 "E AmpMod PB In Env"
int8 "F AmpMod PB In Env"
int8 "X AmpMod PB In Env"
int8 "Z AmpMod PB In Env"

int8 "15"

int8 "A AmpMod PB LFO 1"
int8 "B AmpMod PB LFO 1"
int8 "C AmpMod PB LFO 1"
int8 "D AmpMod PB LFO 1"
int8 "E AmpMod PB LFO 1"
int8 "F AmpMod PB LFO 1"
int8 "X AmpMod PB LFO 1"
int8 "Z AmpMod PB LFO 1"

int8 "u8-2"

int8 "A AmpMod PB LFO 1 AT"
int8 "B AmpMod PB LFO 1 AT"
int8 "C AmpMod PB LFO 1 AT"
int8 "D AmpMod PB LFO 1 AT"
int8 "E AmpMod PB LFO 1 AT"
int8 "F AmpMod PB LFO 1 AT"
int8 "X AmpMod PB LFO 1 AT"
int8 "Z AmpMod PB LFO 1 AT"

int8 "u8-3"

int8 "A AmpMod PB LFO 1 Mod"
int8 "B AmpMod PB LFO 1 Mod"
int8 "C AmpMod PB LFO 1 Mod"
int8 "D AmpMod PB LFO 1 Mod"
int8 "E AmpMod PB LFO 1 Mod"
int8 "F AmpMod PB LFO 1 Mod"
int8 "X AmpMod PB LFO 1 Mod"
int8 "Z AmpMod PB LFO 1 Mod"

int8 "u8-4"

int8 "A AmpMod PB LFO 1 Breath"
int8 "B AmpMod PB LFO 1 Breath"
int8 "C AmpMod PB LFO 1 Breath"
int8 "D AmpMod PB LFO 1 Breath"
int8 "E AmpMod PB LFO 1 Breath"
int8 "F AmpMod PB LFO 1 Breath"
int8 "X AmpMod PB LFO 1 Breath"
int8 "Z AmpMod PB LFO 1 Breath"

int8 "u8-6"

int8 "A AmpMod PB LFO 1 Ctrl 1"
int8 "B AmpMod PB LFO 1 Ctrl 1"
int8 "C AmpMod PB LFO 1 Ctrl 1"
int8 "D AmpMod PB LFO 1 Ctrl 1"
int8 "E AmpMod PB LFO 1 Ctrl 1"
int8 "F AmpMod PB LFO 1 Ctrl 1"
int8 "X AmpMod PB LFO 1 Ctrl 1"
int8 "Z AmpMod PB LFO 1 Ctrl 1"

int8 "u8-5"

int8 "A AmpMod PB LFO 1 Ctrl 2"
int8 "B AmpMod PB LFO 1 Ctrl 2"
int8 "C AmpMod PB LFO 1 Ctrl 2"
int8 "D AmpMod PB LFO 1 Ctrl 2"
int8 "E AmpMod PB LFO 1 Ctrl 2"
int8 "F AmpMod PB LFO 1 Ctrl 2"
int8 "X AmpMod PB LFO 1 Ctrl 2"
int8 "Z AmpMod PB LFO 1 Ctrl 2"

int8 "u8-7"

int8 "A AmpMod PB LFO 2"
int8 "B AmpMod PB LFO 2"
int8 "C AmpMod PB LFO 2"
int8 "D AmpMod PB LFO 2"
int8 "E AmpMod PB LFO 2"
int8 "F AmpMod PB LFO 2"
int8 "X AmpMod PB LFO 2"
int8 "Z AmpMod PB LFO 2"

int8 "u8-8"

int8 "A AmpMod PB LFO 2 AT"
int8 "B AmpMod PB LFO 2 AT"
int8 "C AmpMod PB LFO 2 AT"
int8 "D AmpMod PB LFO 2 AT"
int8 "E AmpMod PB LFO 2 AT"
int8 "F AmpMod PB LFO 2 AT"
int8 "X AmpMod PB LFO 2 AT"
int8 "Z AmpMod PB LFO 2 AT"

int8 "u8-9"

int8 "A AmpMod PB LFO 2 Mod"
int8 "B AmpMod PB LFO 2 Mod"
int8 "C AmpMod PB LFO 2 Mod"
int8 "D AmpMod PB LFO 2 Mod"
int8 "E AmpMod PB LFO 2 Mod"
int8 "F AmpMod PB LFO 2 Mod"
int8 "X AmpMod PB LFO 2 Mod"
int8 "Z AmpMod PB LFO 2 Mod"

int8 "u8-10"

int8 "A AmpMod PB LFO 2 Breath"
int8 "B AmpMod PB LFO 2 Breath"
int8 "C AmpMod PB LFO 2 Breath"
int8 "D AmpMod PB LFO 2 Breath"
int8 "E AmpMod PB LFO 2 Breath"
int8 "F AmpMod PB LFO 2 Breath"
int8 "X AmpMod PB LFO 2 Breath"
int8 "Z AmpMod PB LFO 2 Breath"

int8 "u8-11"

int8 "A AmpMod PB LFO 2 Ctrl 1"
int8 "B AmpMod PB LFO 2 Ctrl 1"
int8 "C AmpMod PB LFO 2 Ctrl 1"
int8 "D AmpMod PB LFO 2 Ctrl 1"
int8 "E AmpMod PB LFO 2 Ctrl 1"
int8 "F AmpMod PB LFO 2 Ctrl 1"
int8 "X AmpMod PB LFO 2 Ctrl 1"
int8 "Z AmpMod PB LFO 2 Ctrl 1"

int8 "u8-12"

int8 "A AmpMod PB LFO 2 Ctrl 2"
int8 "B AmpMod PB LFO 2 Ctrl 2"
int8 "C AmpMod PB LFO 2 Ctrl 2"
int8 "D AmpMod PB LFO 2 Ctrl 2"
int8 "E AmpMod PB LFO 2 Ctrl 2"
int8 "F AmpMod PB LFO 2 Ctrl 2"
int8 "X AmpMod PB LFO 2 Ctrl 2"
int8 "Z AmpMod PB LFO 2 Ctrl 2"

int8 "u8-21"

int8 "A AmpMod PB LFO 2 Ctrl ?"
int8 "B AmpMod PB LFO 2 Ctrl ?"
int8 "C AmpMod PB LFO 2 Ctrl ?"
int8 "D AmpMod PB LFO 2 Ctrl ?"
int8 "E AmpMod PB LFO 2 Ctrl ?"
int8 "F AmpMod PB LFO 2 Ctrl ?"
int8 "X AmpMod PB LFO 2 Ctrl ?"
int8 "Z AmpMod PB LFO 2 Ctrl ?"

int8 "u8-30"
