float "Overdrive: On/Off"
float "Overdrive: Drive"
float "Overdrive: Tone"
float "Overdrive: Bass"
float "Overdrive: Volume"

float "TubeAmp: On/Off"
float "TubeAmp: Drive"
float "TubeAmp: Volume"

float "Cabinet: On/Off"
float "Cabinet: Type"
float "Cabinet: Size"
float "Cabinet: Air"
float "Cabinet: Bass"
float "Cabinet: Treble"

float "ShelfEQ: On/Off"
float "ShelfEQ: Low Frequency"
float "ShelfEQ: Low Gain"
float "ShelfEQ: High Frequency"
float "ShelfEQ: High Gain"
float "ShelfEQ: Volume"

float "PeakEQ: On/Off"
float "PeakEQ: Frequency 1"
float "PeakEQ: Gain 1"
float "PeakEQ: Quality 1"
float "PeakEQ: Frequency 2"
float "PeakEQ: Gain 2"
float "PeakEQ: Quality 2"
float "PeakEQ: Volume"

float "TalkWah: On/Off"
float "TalkWah: Mouth"
float "TalkWah: ModWheel"
float "TalkWah: Size"
float "TalkWah: Bright"

float "Phaser: On/Off "
float "Phaser: Modulation Rate"
float "Phaser: Color"
float "Phaser: Rotate"
float "Phaser: Sweep Minimum"
float "Phaser: Sweep Maximum"
float "Phaser: MIDI Tempo Sync"
float "Phaser: Dry/Wet"
float "Phaser: Invert"
float "Phaser: Notches"

float "Flanger: On/Off"
float "Flanger: Modulation Rate"
float "Flanger: Static"
float "Flanger: Modulation Depth"
float "Flanger: Color"
float "Flanger: Rotate"
float "Flanger: MIDI Tempo Sync"
float "Flanger: Invert"
float "Flanger: Dry/Wet"

float "Tremolo: On/Off"
float "Tremolo: Rate"
float "Tremolo: Intensity"
float "Tremolo: MIDI Tempo Sync"
float "Tremolo: Stereo Panning"
float "Tremolo: Pulse Width"
float "Tremolo: Attack"
float "Tremolo: Decay"

float "Reverb: On/Off"
float "Reverb: Dry/Wet"
float "Reverb: Bright"
float "Reverb: RoomSize"
float "Reverb: Treble"

float "PsycheDelay: On/Off"
float "PsycheDelay: Dry/Wet"
float "PsycheDelay: Delay Time"
float "PsycheDelay: Reverse Delay"
float "PsycheDelay: Delay Detune"
float "PsycheDelay: Feedback"

float "PsycheDelay: ?"

float "PsycheDelay: Delay Pitch Shift"
float "PsycheDelay: MIDI Tempo Sync"
float "PsycheDelay: Stereo"

float "Delay: Delay Time"
float "Delay: Diffusion"
float "Delay: Modulation Depth"
float "Delay: Feedback"
float "Delay: High Cut"
float "Delay: Low Cut"
float "Delay: Invert"
float "Delay: On/Off"
float "Delay: Dry/Wet"
float "Delay: Modulation Rate"
float "Delay: MIDI Tempo Sync"
float "Delay: Sync Delays"
